version: 2

env:
  - CGO_ENABLED=0

builds:
  - id: minio
    main: .
    binary: minio
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    flags:
      - -tags=kqueue
      - -trimpath
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - id: minio
    ids:
      - minio
    name_template: "minio_{{ .Env.PKG_VERSION }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - id: minio-amd64
    ids:
      - minio
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates:
      - "sulin37392/minio:{{ .Tag }}-amd64"
      - "sulin37392/minio:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    extra_files:
      - dockerscripts/docker-entrypoint.sh
      - LICENSE
      - CREDITS

  - id: minio-arm64
    ids:
      - minio
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates:
      - "sulin37392/minio:{{ .Tag }}-arm64"
      - "sulin37392/minio:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    extra_files:
      - dockerscripts/docker-entrypoint.sh
      - LICENSE
      - CREDITS

docker_manifests:
  - name_template: "sulin37392/minio:{{ .Tag }}"
    image_templates:
      - "sulin37392/minio:{{ .Tag }}-amd64"
      - "sulin37392/minio:{{ .Tag }}-arm64"
  - name_template: "sulin37392/minio:latest"
    image_templates:
      - "sulin37392/minio:latest-amd64"
      - "sulin37392/minio:latest-arm64"

checksum:
  name_template: "minio_{{ .Env.PKG_VERSION }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: sulin37392
    name: minio
  draft: false
  prerelease: false
  mode: replace
  replace_existing_artifacts: true
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"

announce:
  skip: true
